---
title: "WQI Shiny"
output: 
  flexdashboard::flex_dashboard
runtime: shiny
---

```{r global, include = FALSE, message = F, warning = F}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F, echo = F)

# packages
library(shiny)
library(tidyverse)
library(randomForest)
library(gridExtra)
library(flexdashboard)
# library(WQI)
devtools::load_all('../WQI/.')
library(mapview)
library(leaflet)
library(sf)
library(shinyWidgets)

# source functions and data
source("R/funcs.R")
data(alldatavg)
data(sheds)
data(cntys)

# numeric variable names
numnms <- c('CSCI', 'ASCI', 'TN2', 'TP', 'Cond', 'indexscore_cram', 'PCT_SAFN', 'H_AqHab', 'H_SubNat',  'Ev_FlowHab', 'XCMG')
numlab <- c('CSCI', 'ASCI', 'Total nitrogen', 'Total phosphorus', 'Conductivity', 'CRAM index score', '% sands and fines', 'Diversity of aquatic habitat', 'Diversity of substrate', 'Evenness of flow habitat types', 'Riparian veg. cover')
names(numnms) <- numlab

# color lims
cscilim <- c(0, 0.79, 1, 1.5)
ascilim <- c(0, 33, 66, 100)
tnlim <- c(34, 22, 11, 0)
tplim <- c(4, 3, 1.5, 0)
condlim <- c(7050, 4700, 2350, 0)
cramlim <- c(0, 33, 66, 100)
safnlim <- c(600, 66, 33, 0)
aqhablim <- c(0, 0.87, 1.74, 2.6)
subnatlim <- c(0, 0.87, 1.74, 2.6)
flowhablim <- c(0, 0.33, 0.66, 1)
veglim <- c(0, 100, 200, 300)
```

```{r reactives}
# selected site for results
cats <- reactive({

  req(nrow(sitedat()) > 0)
  
  # inputs
  sitedat <- sitedat()
  
  # subset
  out <- sitedat %>% 
    filter(MasterID %in% selsit)
  
  return(out)
  
  })

# choices for spatial filter
spaflt <- reactive({
  
  # input
  flby <- input$flby
  
  if(flby == 'SMC regions')
    out <- sheds %>% 
      rename(polylab = SMC_Name)
          
  if(flby == 'Counties')
    out <- cntys %>% 
      rename(polylab = cnty)
  
  out <- out %>% 
    pull(polylab) %>% 
    sort %>% 
    as.character
  
  return(out)
  
})

# selected shed or county polygons, filtered
polys <- reactive({
  
  # inputs
  flby <- input$flby
  flts <- input$flts
      
  if(flby == 'SMC regions')
    out <- sheds %>% 
      rename(pllb = SMC_Name)

  if(flby == 'Counties')
    out <- cntys %>% 
      rename(pllb = cnty)
  
  # filter by selection
  out <- out %>% 
    filter(pllb %in% flts)
  
  return(out)
  
})

# filter site data by spatial 
sitedat <- reactive({
  
  # input
  polys <- polys()
  
  out <- alldatavg[polys, ]
  
  return(out)
  
})

# distribution of conditions for selected sites given spatial filter
dstdat <- reactive({
  
  # input
  sitedat <- sitedat()

  # aggregate 
  out <- sitedat
  st_geometry(out) <- NULL
  out <- out %>% 
    select_if(is.numeric) %>% 
    gather('var', 'val') %>% 
    filter(var %in% numnms) %>% 
    mutate(
      var = factor(var, levels = numnms, labels = names(numnms))
    )
  
  return(out)
  
})

# selected site data but in long format
catslng <- reactive({
  
  # input
  cats <- cats()
  
  # format selected data
  st_geometry(cats) <- NULL
  out <- cats %>% 
    select_if(is.numeric) %>% 
    gather('var', 'val') %>% 
    filter(var %in% numnms) %>% 
    mutate(
      var = factor(var, levels = numnms, labels = names(numnms))
    )
  
  return(out)
  
})

```

```{r outputobj}
output$map <- renderLeaflet({

  # input
  tomap <- input$tomap
  polys <- polys()
  sitedat <- sitedat()
  
  req(nrow(polys) > 0)
  
  # assign colors
  cols <- getdsccol(sitedat[[tomap]])
  names(cols) <- NULL
  names(sitedat)[names(sitedat) %in% tomap] <- 'toshw'
  
  # legend stuff
  legcols <- getdsccol(palfac = tomap)

  mapview(polys, fill = F, label = polys$pllb, homebutton = F, popup = NULL) %>% 
    .@map %>% 
    removeMouseCoordinates() %>%
    addCircleMarkers(
      data = sitedat, 
      layerId = ~MasterID,
      stroke = TRUE,
      color = 'black',
      fill = TRUE,
      fillColor = cols,
      radius=5, 
      weight = 1,
      fillOpacity = 1,
      label = ~paste0(MasterID, ': ', toshw)
    ) %>% 
    addLegend("bottomleft", colors = legcols$col, labels = legcols$nms, opacity = 1)

})

# leaflet proxy for marker select
map <- leafletProxy("map")

# binding for marker select
makeReactiveBinding('selsit')

# the selection
observeEvent(input$map_marker_click, {
  selsit <<- input$map_marker_click$id
})

observeEvent(input$map_marker_click, {

  # inputs
  tomap <- input$tomap
  sitedat <- sitedat()
  
  # colors
  cols <- getdsccol(sitedat[[tomap]])
  names(cols) <- NULL
  names(sitedat)[names(sitedat) %in% tomap] <- 'toshw'
  
  # filter the pour points by selection
  selsitplo <- sitedat %>% 
    filter(MasterID %in% selsit)
  selsitplocol <- getdsccol(selsitplo[['toshw']])
  names(selsitplocol) <- NULL
  
  # clear markers on input select, add all points and selected point
  map <- map %>% 
    clearMarkers() %>% 
    addCircleMarkers(
      data = sitedat, 
      layerId = ~MasterID,
      stroke = TRUE,
      color = 'black',
      fill = TRUE,
      fillColor = cols,
      radius=5, 
      weight = 1,
      fillOpacity = 1,
      label = ~paste0(MasterID, ': ', toshw)
    ) %>% 
    addCircleMarkers(
      data = selsitplo, 
      layerId = ~MasterID,
      stroke = TRUE,
      color = 'black',
      fillColor = selsitplocol,
      fill = TRUE,
      radius=10, 
      weight = 6,
      fillOpacity = 1,
      label = ~paste0(MasterID, ': ', toshw)
    )
      
})

##
# WQI descriptor outputs
output$overall <- flexdashboard::renderValueBox({
  req(nrow(cats()) > 0)
  txtin <- cats()$StreamHealthIndex
  colin <- getdsccol(txtin)
  flexdashboard::valueBox(tags$p(txtin, style = "font-size: 70%"), icon = 'glyphicon-plus', color = colin)
  })
output$biolcon <- flexdashboard::renderValueBox({
  req(nrow(cats()) > 0)
  txtin <- cats()$BiologicalCondition
  colin <- getdsccol(txtin)
  flexdashboard::valueBox(tags$p(txtin, style = "font-size: 70%"), icon = 'glyphicon-leaf', color = colin)
  })
output$strscon <- flexdashboard::renderValueBox({
  req(nrow(cats()) > 0)
  txtin <- cats()$OverallStressCondition
  colin <- getdsccol(txtin)
  flexdashboard::valueBox(tags$p(txtin, style = "font-size: 70%"), icon = 'glyphicon-flash', color = colin)
  })
output$strsdet <- flexdashboard::renderValueBox({
  req(nrow(cats()) > 0)
  txtin <- cats()$OverallStressCondition_detail
  colin <- getdsccol(txtin)
  flexdashboard::valueBox(tags$p(txtin, style = "font-size: 70%"), icon = 'glyphicon-flash', color = colin)
  })

##
# probability gauge outputs
output$pchemhab <- renderGauge({
  
    val <- round(100 * cats()$pChemHab, 1)
    gauge(val, min = 0, max = 100, symbol = '%', gaugeSectors(
     success = c(0, 33), warning = c(33, 66), danger = c(66, 100)
    ))
             
  })
output$pchem <- renderGauge({
  
  val <- round(100 * cats()$pChem, 1)
  gauge(val, min = 0, max = 100, symbol = '%', gaugeSectors(
     success = c(0, 33), warning = c(33, 66), danger = c(66, 100)
  ))
  
})
output$phab <- renderGauge({
  val <- round(100 * cats()$pHab, 1)
  gauge(val, min = 0, max = 100, symbol = '%', gaugeSectors(
     success = c(0, 33), warning = c(33, 66), danger = c(66, 100)
  ))
  
})

##
# detail gauge outputs
output$csci <- renderGauge({
  val <- round(cats()$CSCI, 1)
  gauge(val, min = cscilim[1], max = cscilim[4], gaugeSectors(
     danger = cscilim[c(1, 2)], warning = cscilim[c(2, 3)], success = cscilim[c(3, 4)])
  )
})
output$asci <- renderGauge({
  val <- round(cats()$ASCI, 1)
  gauge(val, min = ascilim[1], max = ascilim[4], gaugeSectors(
     danger = ascilim[c(1, 2)], warning = ascilim[c(2, 3)], success = ascilim[c(3, 4)])
  )
})
output$tn <- renderGauge({
  val <- round(cats()$TN2, 1)
  gauge(val, min = tnlim[1], max = tnlim[4], gaugeSectors(
     danger = tnlim[c(3, 4)], warning = tnlim[c(2, 3)], success = tnlim[c(1, 2)])
  )
})
output$tp <- renderGauge({
  val <- round(cats()$TP, 1)
  gauge(val, min = 0, max = 4.5, gaugeSectors(
     danger = c(3, 4.5), warning = c(1.5, 3), success = c(0, 1.5))
  )
})
output$cond <- renderGauge({
  val <- round(cats()$Cond, 1)
  gauge(val, min = 0, max = 7050, gaugeSectors(
     danger = c(4700, 7050), warning = c(2350, 4700), success = c(0, 2350))
  )
})
output$cram <- renderGauge({
  val <- round(cats()$indexscore_cram, 1)
  gauge(val, min = 0, max = 100, gaugeSectors(
     danger = c(0, 33), warning = c(33, 66), success = c(66, 100))
  )
})
output$safn <- renderGauge({
  val <- round(cats()$PCT_SAFN, 1)
  gauge(val, min = 0, max = 100, gaugeSectors(
     danger = c(66, 100), warning = c(33, 66), success = c(0, 33))
  )
})
output$aqhab <- renderGauge({
  val <- round(cats()$H_AqHab, 1)
  gauge(val, min = 0, max = 2.6, gaugeSectors(
     danger = c(0, .87), warning = c(0.87, 1.74), success = c(1.74, 2.6))
  )
})
output$subnat <- renderGauge({
  val <- round(cats()$H_SubNat, 1)
  gauge(val, min = 0, max = 2.6, gaugeSectors(
     danger = c(0, .87), warning = c(0.87, 1.74), success = c(1.74, 2.6))
  )
})
output$flowhab <- renderGauge({
  val <- round(cats()$Ev_FlowHab, 1)
  gauge(val, min = 0, max = 1, gaugeSectors(
     danger = c(0, .33), warning = c(0.33, 0.66), success = c(0.66, 1))
  )
})
output$veg <- renderGauge({
  val <- round(cats()$XCMG, 1)
  gauge(val, min = 0, max = 300, gaugeSectors(
     danger = c(0, 100), warning = c(100, 200), success = c(200, 300))
  )
})

##
# plots 

# chemistry wq plots
output$plochem <- renderPlot({
  
  # inputs
  opt_vrs <- cats()
  st_geometry(opt_vrs) <- NULL
  opt_vrs <- opt_vrs %>% 
    ungroup %>% 
    select(TN2, TP, Cond) %>% 
    as.list
  plovrs <- c(input$chem1, input$chem2)

  # the plot
  strs_surf(xvar = plovrs[1], yvar = plovrs[2], mod = 'wq_mod', mod_in = 'wqgam', opt_vrs = opt_vrs)
  
}, height = 500)

# chemistry wq plots
output$plohab <- renderPlot({
  
  # inputs
  opt_vrs <- cats()
  st_geometry(opt_vrs) <- NULL
  opt_vrs <- opt_vrs %>% 
    ungroup %>% 
    select(indexscore_cram, PCT_SAFN, H_AqHab, H_SubNat, Ev_FlowHab, XCMG) %>% 
    as.list
  plovrs <- c(input$hab1, input$hab2)

  # the plot
  strs_surf(xvar = plovrs[1], yvar = plovrs[2], mod = 'hab_mod', mod_in = 'habgam', opt_vrs = opt_vrs)
  
}, height = 500)

# distribution boxplots, biology
output$plodstbio <- renderPlot({
  
  # only do it a site has been selected
  req(nrow(catslng()) > 0)
  
  # input
  dstdat <- dstdat()
  catslng <- catslng()
  
  # filter biodata
  selvr <- c('CSCI', 'ASCI')
  toplodst <- dstdat %>% 
    filter(var %in% selvr)
  toplocats <- catslng %>% 
    filter(var %in% selvr)
  
  p <- ggplot(toplodst, aes(x = var, y = val)) + 
    geom_boxplot() + 
    geom_hline(data = toplocats, aes(yintercept = val), colour = 'tomato1', size = 1) +
    facet_wrap(~var, scales = 'free', ncol = length(selvr)) + 
    theme_bw() + 
    theme(
      strip.background = element_blank(),
      strip.text.x = element_blank(), 
      axis.title = element_blank() 
    )
  
  return(p)
  
}, width = 400)

# distribution boxplots, chemistry
output$plodstchm <- renderPlot({
  
  # only do it a site has been selected
  req(nrow(catslng()) > 0)
  
  # input
  dstdat <- dstdat()
  catslng <- catslng()
  
  # filter biodata
  selvr <-  c('Total nitrogen', 'Total phosphorus', 'Conductivity')
  toplodst <- dstdat %>% 
    filter(var %in% selvr)
  toplocats <- catslng %>% 
    filter(var %in% selvr)
  
  p <- ggplot(toplodst, aes(x = var, y = val)) + 
    geom_boxplot() + 
    geom_hline(data = toplocats, aes(yintercept = val), colour = 'tomato1', size = 1) +
    facet_wrap(~var, scales = 'free', ncol = length(selvr)) + 
    theme_bw() + 
    theme(
      strip.background = element_blank(),
      strip.text.x = element_blank(), 
      axis.title = element_blank() 
    )
  
  return(p)
  
}, width = 600)

# distribution boxplots, habitat
output$plodsthab <- renderPlot({
  
  # only do it a site has been selected
  req(nrow(catslng()) > 0)
  
  # input
  dstdat <- dstdat()
  catslng <- catslng()
  
  # filter biodata
  selvr <-  c('CRAM index score', '% sands and fines', 'Diversity of aquatic habitat', 'Diversity of substrate', 'Evenness of flow habitat types', 'Riparian veg. cover')
  toplodst <- dstdat %>% 
    filter(var %in% selvr)
  toplocats <- catslng %>% 
    filter(var %in% selvr)
  
  p <- ggplot(toplodst, aes(x = var, y = val)) + 
    geom_boxplot() + 
    geom_hline(data = toplocats, aes(yintercept = val), colour = 'tomato1', size = 1) +
    facet_wrap(~var, scales = 'free', ncol = length(selvr)) + 
    theme_bw() + 
    theme(
      strip.background = element_blank(),
      strip.text.x = element_blank(), 
      axis.title = element_blank() 
    )
  
  return(p)
  
})
```

Sidebar {.sidebar data-width=700}
===========================================================

```{r}
# select spatial filter
column(width = 12, 
  
  column(width = 6, 
         
    selectInput('flby', 'Filter by:', choices = c('SMC regions', 'Counties'))
                
  ), 
  
  column(width = 6, 
         
    renderUI({
      
      # input
      spaflt <- spaflt()

      pickerInput(inputId = "flts", label = 'Select spatial filters:', choices = spaflt,
        options = list(`actions-box` = TRUE, size = 20), selected = spaflt, multiple = TRUE)      
      
    })
           
  )
       
)

# select index output on map and site selection text
column(width = 12, 
       
  column(width = 6, 
                
    selectInput('tomap', 'WQI output:', 
      choices = list(
        'Overall' = 'StreamHealthIndex', 
        'Biological condition' = 'BiologicalCondition',
        'Stress condition' = 'OverallStressCondition', 
        'Stress condition detail' = 'OverallStressCondition_detail'
      ), 
      selected = 'Overall'
    )
  
  ),
  
  column(width = 6, 
         
    renderText(paste0('Selected site: ', selsit))
    
  )
  
)
```

```{r}
leafletOutput('map', height = 590)
```

Overview
=====================================

Column {data-width=500}
------------------------------------------------------------------------

###  Overall

```{r}
flexdashboard::valueBoxOutput('overall')
```

### Biological condition

```{r}
flexdashboard::valueBoxOutput('biolcon')
```

### Stress condition

```{r}
flexdashboard::valueBoxOutput('strscon')
```

### Stress condition detail

```{r}
flexdashboard::valueBoxOutput('strsdet')
```

### Probability of stress

```{r}
 column(width = 12,
                  shinydashboard::box(gaugeOutput('pchemhab'), title = HTML('<h4><i>Prob. of overall stress:</i></h4>'), width = 4),
                  shinydashboard::box(gaugeOutput('pchem'), title = HTML('<h4><i>Prob. of chemistry stress:</i></h4>'), width = 4),
                  shinydashboard::box(gaugeOutput('phab'), title = HTML('<h4><i>Prob. of habitat stress:</i></h4>'), width = 4)
           )
```

Details
===================================== 

Column 
-----------------------------------------------------------------------

### Biology

```{r}
 column(width = 12,
                  shinydashboard::box(gaugeOutput('csci'), title = HTML('<h4><i>CSCI:</i></h4>'), width = 3),
                  shinydashboard::box(gaugeOutput('asci'), title = HTML('<h4><i>ASCI:</i></h4>'), width = 3)
 )
```

### Chemistry

```{r}
 column(width = 12,
                  shinydashboard::box(gaugeOutput('tn'), title = HTML('<h4><i>Total nitrogen:</i></h4>'), width = 3),
                  shinydashboard::box(gaugeOutput('tp'), title = HTML('<h4><i>Total phosphorus:</i></h4>'), width = 3),
                  shinydashboard::box(gaugeOutput('cond'), title = HTML('<h4><i>Conductivity:</i></h4>'), width = 3)
 )
```

### Habitat

```{r}
 column(width = 12,
                  shinydashboard::box(gaugeOutput('cram', height = '500px'), title = HTML('<h4><i>CRAM index score:</i></h4>'), width = 2),
                  shinydashboard::box(gaugeOutput('safn', height = '500px'), title = HTML('<h4><i>% sands and fines:</i></h4>'), width = 2),
                  shinydashboard::box(gaugeOutput('aqhab', height = '500px'), title = HTML('<h4><i>Diversity of aquatic habitat:</i></h4>'), width = 2),
                  shinydashboard::box(gaugeOutput('subnat', height = '500px'), title = HTML('<h4><i>Diversity of substrate:</i></h4>'), width = 2),
                  shinydashboard::box(gaugeOutput('flowhab', height = '500px'), title = HTML('<h4><i>Evenness of flow habitat types:</i></h4>'), width = 2),
                  shinydashboard::box(gaugeOutput('veg', height = '500px'), title = HTML('<h4><i>Riparian veg. cover:</i></h4>'), width = 2)
 )
```

Relative details
===================================== 

Column 
-----------------------------------------------------------------------

### Biology

```{r}
plotOutput('plodstbio')
```

### Chemistry

```{r}
plotOutput('plodstchm')
```

### Habitat

```{r}
plotOutput('plodsthab')
```

Scenario exploration
===================================================

Rows
------------------------

### Scenario exploration

```{r}
# plot outputs
fluidRow(
  
  column(width = 12, 
         h5('Selected values beyond those on the x and y axes are shown at the plot margins.')
         ),
  
  # chemistry plots
  column(width = 6, 

         # first chem input
         selectInput("chem1", 
           label = 'x-axis chemistry variable', 
           choices = list(
             "Total Nitrogen" = "TN2",
             "Total Phosphorus" = "TP",
             "Conductivity" = "Cond"
           ),
           selected = "TN2"
        ),
  
        # second chem input
        selectInput("chem2", 
                    label = 'y-axis chemistry variable', 
                    choices = list(
                      "Total Nitrogen" = "TN2",
                      "Total Phosphorus" = "TP",
                      "Conductivity" = "Cond"
                    ),
                    selected = "TP"
        ),
        plotOutput('plochem')
      ),
  
  # habitat plots
  column(width = 6, 
         
         # first hab input
         selectInput("hab1", 
                     label = 'x-axis habitat variable', 
                     choices = list(
                       "CRAM" = "indexscore_cram",
                       "% sands and fines" = "PCT_SAFN",
                       "Diversity of aquatic habitats" = "H_AqHab",
                       "Diversity of substrates" = "H_SubNat",
                       "Evenness of flow habitat types" = "Ev_FlowHab",
                       "Riparian veg cover" = "XCMG"
                     ),
                     selected = "indescore_cram"
         ),

         # second hab input
         selectInput("hab2", 
                     label = 'y-axis habitat variable', 
                     choices = list(
                       "CRAM" = "indexscore_cram",
                       "% sands and fines" = "PCT_SAFN",
                       "Diversity of aquatic habitats" = "H_AqHab",
                       "Diversity of substrates" = "H_SubNat",
                       "Evenness of flow habitat types" = "Ev_FlowHab",
                       "Riparian veg cover" = "XCMG"
                     ),
                     selected = "PCT_SAFN"
         ),
         
         plotOutput('plohab')
  )
)
```

