---
title: "SQI calculator"
output: 
  html_document
runtime: shiny
---

[Back to SQI dashboard](https://sccwrp.shinyapps.io/SQI_shiny)

```{r global, include = FALSE, message = F, warning = F}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F, echo = F)

# packages
library(shiny)
library(tidyverse)
library(SQI)
```

```{r, echo = F}
column(12, 
       column(4, 
              numericInput('CSCI', 'CSCI:', value = 1, min = 0, step = 0.1)
              ), 
       column(4, 
              numericInput('ASCI', 'ASCI:', value = 1, min = 0, step = 0.1)
              ), 
       column(4, 
              numericInput('TN', 'Total Nitrogen (mg/L):', value = 5, min = 0, step = 1)
              )
)
column(12, 
       column(4, 
              numericInput('TP', 'Total Phosphorus (mg/L):', value = 1, min = 0, step = 1)
              ),
       column(4, 
              numericInput('Cond', 'Conductivity (uS/cm):', value = 500, min = 0, step = 10)
              ),
       column(4, 
              numericInput('blc', 'CRAM, buffer landscape condition:', value =50, min = 0, step = 10, max = 100)
              )
       )
column(12, 
       column(4, 
              numericInput('ps', 'CRAM, physical structure:', value = 50, min = 0, step = 10, max = 100)
              ),
       column(4, 
              numericInput('PCT_SAFN', 'IPI, % sands and fines:', value = 0.5, min = 0, step = 0.1, max = 1)
              )
       )
column(12, 
       column(4, actionButton("run", "Run!"))
)
```

```{r, echo = F}
res <- eventReactive(input$run, {

  # inputs
  out <- reactiveValuesToList(input) %>% 
    enframe('var', 'val') %>% 
    filter(!var %in% 'run') %>% 
    unnest %>% 
    spread(var, val) %>% 
    sqi %>% 
    dplyr::select(pChem, pHab, pChemHab, BiologicalCondition, OverallStressCondition_detail, StreamHealthIndex) %>% 
    rename(
      pOverall = pChemHab,
      `Biological Condition` = BiologicalCondition,
      `Stress Condition` = OverallStressCondition_detail, 
      SQI = StreamHealthIndex
    )
  
  return(out)
  
})
```

```{r, echo = F}
renderTable({res()})
```


