---
title: "WQI Shiny"
output: 
  flexdashboard::flex_dashboard
runtime: shiny
---

```{r global, include = FALSE, message = F, warning = F}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F, echo = F)

# packages
library(shiny)
library(tidyverse)
library(randomForest)
library(gridExtra)
library(flexdashboard)
library(WQI)
library(mapview)
library(leaflet)

# source functions and data
source("R/funcs.R")
data(alldat)
data(sheds)

# length values for sequence plot data
len.x<-20

# chem plot data
plot.dat.chem <- crossing(
  TN2=seq(from=0,to=1.5, length.out=len.x*2.5),
  TP=seq(from=0,to=1, length.out=len.x*2.5),
  Cond=seq(from=0,to=2000, length.out=len.x*2.5)
)

plot.dat.chem$pChem<-predict(wqrfwp, newdata=plot.dat.chem, type="prob")[,2]

# hab plot data
plot.dat.hab<-expand.grid(
  indexscore_cram=seq(from=24,to=100, length.out=len.x/2),
  PCT_SAFN=seq(from=0,to=100, length.out=len.x/2),
  H_AqHab=seq(from=0,to=2.5, length.out=len.x/2),
  H_SubNat=seq(from=0,to=2.5, length.out=len.x/2),
  Ev_FlowHab=seq(from=0,to=1, length.out=len.x/2),
  XCMG=seq(from=0,to=264, length.out=len.x/2)
)

plot.dat.hab$pHab<-predict(habrfwp, newdata=plot.dat.hab, type="prob")[,2]
```

```{r reactives}
# values to predict
toprd <- reactive({

  out <- data.frame(
    CSCI = input$csci,
    ASCI = input$asci,
    TN2 = input$tn,
    TP = input$tp,
    Cond = input$cond,
    indexscore_cram = input$cram,
    PCT_SAFN = input$safn,
    H_AqHab = input$aqhab,
    H_SubNat = input$subnat,
    Ev_FlowHab = input$flowhab,
    XCMG = input$veg
  )

  return(out)

})

# categories from predictions
cats <- reactive({

  if(is.null(selsit)) return()
  
  out <- alldat %>% 
    filter(MasterID %in% selsit)
  
  return(out)
  
  })
```

```{r outputobj}
##
# gauge outputs
output$pchemhab <- renderGauge({
  
    val <- round(100 * cats()$pChemHab, 1)
    gauge(val, min = 0, max = 100, symbol = '%', gaugeSectors(
     success = c(67, 100), warning = c(33, 66), danger = c(0, 32)
    ))
             
  })
output$pchem <- renderGauge({
  
  val <- round(100 * cats()$pChem, 1)
  gauge(val, min = 0, max = 100, symbol = '%', gaugeSectors(
     success = c(67, 100), warning = c(33, 66), danger = c(0, 32)
  ))
  
})
output$phab <- renderGauge({
  
  val <- round(100 * cats()$pHab, 1)
  gauge(val, min = 0, max = 100, symbol = '%', gaugeSectors(
     success = c(67, 100), warning = c(33, 66), danger = c(0, 32)
  ))
  
})

##
# WQI descriptor outputs
output$overall <- flexdashboard::renderValueBox({
  txtin <- cats()$StreamHealthIndex
  colin <- getdsccol(txtin)
  flexdashboard::valueBox(tags$p(txtin, style = "font-size: 70%"), icon = 'glyphicon-plus', color = colin)
  })
output$biolcon <- flexdashboard::renderValueBox({
  txtin <- cats()$BiologicalCondition
  colin <- getdsccol(txtin)
  flexdashboard::valueBox(tags$p(txtin, style = "font-size: 70%"), icon = 'glyphicon-leaf', color = colin)
  })
output$strscon <- flexdashboard::renderValueBox({
  txtin <- cats()$OverallStressCondition
  colin <- getdsccol(txtin)
  flexdashboard::valueBox(tags$p(txtin, style = "font-size: 70%"), icon = 'glyphicon-flash', color = colin)
  })
output$strsdet <- flexdashboard::renderValueBox({
  txtin <- cats()$OverallStressCondition_detail
  colin <- getdsccol(txtin)
  flexdashboard::valueBox(tags$p(txtin, style = "font-size: 70%"), icon = 'glyphicon-flash', color = colin)
  })

##
# plots 

# chemistry wq plots
output$plochem <- renderPlot({
  
  mydf.prediction <- cats()
  
  # names of variables to plot
  plovrs <- c(input$chem1, input$chem2)
  
  # names of variables to hold constant
  convrs <- names(plot.dat.chem)[!names(plot.dat.chem) %in% c(plovrs, 'pChem')]
  
  # selected conditional variables
  selcon <- mydf.prediction[, convrs, drop = F] %>% 
    gather('var', 'val')

  # estimated conditional variables, closest values to sel
  selconclo <- plot.dat.chem[, convrs, drop = F] %>% 
    gather('var', 'val') %>% 
    left_join(selcon, by = 'var') %>% 
    mutate(minv = abs(val.x - val.y)) %>% 
    group_by(var) %>% 
    filter(minv == min(minv)) %>% 
    unique %>% 
    filter(!duplicated(var)) %>% 
    select(var, val.x) %>% 
    rename(val = val.x) %>% 
    mutate(val = round(val, 5)) %>% 
    unite('con', var, val, sep = ' == ') %>% 
    unlist %>% 
    paste(collapse = ' & ')
  
  # filtered chem data to plot
  toplo <- plot.dat.chem %>% 
    mutate_if(is.numeric, round, 5) %>% 
    filter_(selconclo)

  # actual selected values and prob est
  my.pred.plot<-mydf.prediction
  my.pred.plot$TN2<-pmin(max(plot.dat.chem$TN2),my.pred.plot$TN2)
  my.pred.plot$TP<-pmin(max(plot.dat.chem$TP),my.pred.plot$TP)
  my.pred.plot$Cond<-pmin(max(plot.dat.chem$Cond),my.pred.plot$Cond)
  
  # title
  titlvl <- selcon %>% 
    unite('con', var, val, sep = ' ') %>% 
    unlist %>% 
    paste(collapse = ', ')
  
  p1 <- ggplot(data = toplo, aes_string(x=plovrs[1], y=plovrs[2]))+
    geom_tile(aes(fill=pChem))+
    scale_fill_gradient2(low="#d7191c", mid="#ffffbf", high="#2c7bb6", midpoint=0.5)+
    geom_point(data=my.pred.plot, shape=21, size = 5, fill="white")+
    theme_minimal(base_size = 14, base_family = 'serif') +
    scale_x_continuous(expand = c(0, 0)) +
    scale_y_continuous(expand = c(0, 0)) +
    ggtitle(paste0('Constant values: ', titlvl))
  
  p1
  
}, height = 450)

# chemistry wq plots
output$plohab <- renderPlot({
  
  mydf.prediction <- cats()
  
  # names of variables to plot
  plovrs <- c(input$hab1, input$hab2)
  
  # names of variables to hold constant
  convrs <- names(plot.dat.hab)[!names(plot.dat.hab) %in% c(plovrs, 'pHab')]
  
  # selected conditional variables
  selcon <- mydf.prediction[, convrs, drop = F] %>% 
    gather('var', 'val')
  
  # estimated conditional variables, closest values to sel
  selconclo <- plot.dat.hab[, convrs, drop = F] %>% 
    gather('var', 'val') %>% 
    left_join(selcon, by = 'var') %>% 
    mutate(minv = abs(val.x - val.y)) %>% 
    group_by(var) %>% 
    filter(minv == min(minv)) %>% 
    unique %>% 
    filter(!duplicated(var)) %>% 
    select(var, val.x) %>% 
    rename(val = val.x) %>% 
    mutate(val = round(val, 5)) %>% 
    unite('con', var, val, sep = ' == ') %>% 
    unlist %>% 
    paste(collapse = ' & ')
  
  # filtered hab data to plot
  toplo <- plot.dat.hab %>% 
    mutate_if(is.numeric, round, 5) %>% 
    filter_(selconclo)

  # actual selected values and prob est
  my.pred.plot<-mydf.prediction
  my.pred.plot$indexscore_cram<-pmin(max(plot.dat.hab$indexscore_cram),my.pred.plot$indexscore_cram)
  my.pred.plot$PCT_SAFN<-pmin(max(plot.dat.hab$PCT_SAFN),my.pred.plot$PCT_SAFN)
  my.pred.plot$H_AqHab<-pmin(max(plot.dat.hab$H_AqHab),my.pred.plot$H_AqHab)
  my.pred.plot$H_SubNat<-pmin(max(plot.dat.hab$H_SubNat),my.pred.plot$H_SubNat)
  my.pred.plot$Ev_FlowHab<-pmin(max(plot.dat.hab$Ev_FlowHab),my.pred.plot$Ev_FlowHab)
  my.pred.plot$XCMG<-pmin(max(plot.dat.hab$XCMG),my.pred.plot$XCMG)
  
  # title
  titlvl <- selcon %>% 
    unite('con', var, val, sep = ' ') %>% 
    unlist %>% 
    paste(collapse = ', ')
  
  p1 <- ggplot(data = toplo, aes_string(x=plovrs[1], y=plovrs[2]))+
    geom_tile(aes(fill=pHab))+
    scale_fill_gradient2(low="#d7191c", mid="#ffffbf", high="#2c7bb6", midpoint=0.5)+
    geom_point(data=my.pred.plot, shape=21, size = 5, fill="white")+
    theme_minimal(base_size = 14, base_family = 'serif') +
    scale_x_continuous(expand = c(0, 0)) +
    scale_y_continuous(expand = c(0, 0)) +
    ggtitle(paste0('Constant values: ', titlvl))
  
  p1
  
}, height = 450)
```

Map
=====================================

Column {.sidebar}
-----------------------------------------------------------------------

Select the mapping option. 

### Select input

```{r}
selectInput('tomap', 'WQI output:', 
  choices = list(
    'Overall' = 'StreamHealthIndex', 
    'Biological condition' = 'BiologicalCondition',
    'Stress condition' = 'OverallStressCondition', 
    'Stress condition detail' = 'OverallStressCondition_detail'
  ), 
  selected = 'Overall'
)
```

Selected site:

```{r}
renderText({selsit})
```

Row {data-height=500}
------------------------------------------------------------------------

### View selection

```{r}
output$map <- renderLeaflet({

  # input
  tomap <- input$tomap
  cols <- getdsccol(alldat[[tomap]])
  names(cols) <- NULL
  names(alldat)[names(alldat) %in% tomap] <- 'toshw'

  mapview(sheds, fill = F, label = sheds$SMC_Name) %>% 
    .@map %>% 
    # removeMouseCoordinates() %>%
    addCircleMarkers(
      data = alldat, 
      layerId = ~MasterID,
      stroke = TRUE,
      color = 'black',
      fill = TRUE,
      fillColor = cols,
      radius=5, 
      weight = 1,
      fillOpacity = 1,
      label = ~toshw
    )

})

# leaflet proxy for marker select
map <- leafletProxy("map")

# binding for marker select
makeReactiveBinding('selsit')

# the selection
observeEvent(input$map_marker_click, {
  selsit <<- input$map_marker_click$id
})

observeEvent(input$map_marker_click, {
  
  if(is.null(selsit)) return()  

  tomap <- input$tomap
  cols <- getdsccol(alldat[[tomap]])
  names(cols) <- NULL
  names(alldat)[names(alldat) %in% tomap] <- 'toshw'
  
  # filter the pour points by selection
  selsitplo <- alldat %>% 
    filter(MasterID %in% selsit)
  
  # clear markers on input select, add all points and selected point
  map <- map %>% 
    clearMarkers() %>% 
    addCircleMarkers(
      data = alldat, 
      layerId = ~MasterID,
      stroke = TRUE,
      color = 'black',
      fill = TRUE,
      fillColor = cols,
      radius=5, 
      weight = 1,
      fillOpacity = 1,
      label = ~toshw
    ) %>% 
    addCircleMarkers(
      data = selsitplo, 
      layerId = ~MasterID,
      stroke = TRUE,
      color = 'black',
      fill = TRUE,
      fillColor = 'red',
      radius=5, 
      weight = 1,
      fillOpacity = 1,
      label = ~toshw
    )
      
})

leafletOutput('map')
```

Column 
-----------------------------

###  Overall

```{r}
flexdashboard::valueBoxOutput('overall')
```

### Biological condition

```{r}
flexdashboard::valueBoxOutput('biolcon')
```

### Stress condition

```{r}
flexdashboard::valueBoxOutput('strscon')
```

### Stress condition detail

```{r}
flexdashboard::valueBoxOutput('strsdet')
```

Row {data-height=500}
-----------------------------

### Gauges

```{r}
 column(width = 12,
                  shinydashboard::box(gaugeOutput('pchemhab'), title = HTML('<h4><i>Prob. of low overall stress:</i></h4>'), width = 4),
                  shinydashboard::box(gaugeOutput('pchem'), title = HTML('<h4><i>Prob. of low chemistry stress:</i></h4>'), width = 4),
                  shinydashboard::box(gaugeOutput('phab'), title = HTML('<h4><i>Prob. of low habitat stress:</i></h4>'), width = 4)
           )
```

Inputs
===================================== 

Row
-----------------------------------------------------------------------

### Biology

```{r}
numericInput('csci', h5('CSCI score. Enter a number between 0 and ~1.4'), value = 0.45, min = 0, max = 1.5)
numericInput('asci', h5('ASCI score (H20 for now). Enter a number between 0 and 100'), value = 25, min = 0, max = 100)
```

### Chemistry

```{r }
numericInput('tn', h5('Total N (mg/L). Enter a number greater than zero'), value = 10.1, min = 0) 
numericInput('tp', h5('Total P (mg/L). Enter a number greater than zero'), value = 10.001, min = 0)    
numericInput('cond', h5('Specific conductance (uS/cm). Enter a number greater than zero'), value = 450, min = 0)
```

### Habitat

```{r}
numericInput('cram', h5('CRAM score. Enter a number between 0 and 100'), value = 75, min = 0, max = 100) 
numericInput('safn', h5('% sands and fines. Enter a number between 0 and 100'), value = 35, min = 0, max = 100)    
numericInput('aqhab', h5('SW diversity of aquatic habitats. Enter a number between 0 and ~2.5'), value = 1.5, min = 0, max = 2.6)    
numericInput('subnat', h5('SW diversity of streambed substrate. Enter a number between 0 and ~2.5'), value = 1.9, min = 0, max = 2.6) 
numericInput('flowhab', h5('Evenness of flow habitat types (e.g., riffles, pools). Enter a number between zero and 1'), value = 0.5, min = 0, max = 1)    
numericInput('veg', h5('Riparian veg cover. Enter a number from 0 to ~265'), value = 200, min = 0, max = 300)
```

Plots
===================================================

Rows
------------------------

### Plots

```{r}
# plot outputs
fluidRow(
  
  HTML('<p></p>'),
  column(width = 12, 
         h5('Selected values beyond those on the x and y axes are shown at the plot margins.')
         ),
  
  # chemistry plots
  column(width = 6, 
         
         h5('x-axis chemistry variable'),
         
         # first chem input
         selectInput("chem1", 
           label = '', 
           choices = list(
             "Total Nitrogen" = "TN2",
             "Total Phosphorus" = "TP",
             "Conductivity" = "Cond"
           ),
           selected = "TN2"
        ),
  
        h5('y-axis chemistry variable'),
        
        # second chem input
        selectInput("chem2", 
                    label = '', 
                    choices = list(
                      "Total Nitrogen" = "TN2",
                      "Total Phosphorus" = "TP",
                      "Conductivity" = "Cond"
                    ),
                    selected = "TP"
        ),
        plotOutput('plochem')
      ),
  
  # habitat plots
  column(width = 6, 
         
         h5('x-axis habitat variable'),
         
         # first hab input
         selectInput("hab1", 
                     label = '', 
                     choices = list(
                       "CRAM" = "indexscore_cram",
                       "% sands and fines" = "PCT_SAFN",
                       "SW diversity of aquatic habitats" = "H_AqHab",
                       "SW diversity of streambed substrates" = "H_SubNat",
                       "Evenness of flow habitat types" = "Ev_FlowHab",
                       "Riparian veg cover" = "XCMG"
                     ),
                     selected = "indescore_cram"
         ),
         
         h5('y-axis habitat variable'),
         
         # second hab input
         selectInput("hab2", 
                     label = '', 
                     choices = list(
                       "CRAM" = "indexscore_cram",
                       "% sands and fines" = "PCT_SAFN",
                       "SW diversity of aquatic habitats" = "H_AqHab",
                       "SW diversity of streambed substrates" = "H_SubNat",
                       "Evenness of flow habitat types" = "Ev_FlowHab",
                       "Riparian veg cover" = "XCMG"
                     ),
                     selected = "PCT_SAFN"
         ),
         
         plotOutput('plohab')
  )
)
```

